#!/bin/bash 
#
#
# Settings
# Path to BPQ binary directory
bpqbin=$PWD/bpqbin
# Name of binary to pull as well as use
binary=pilinbpq
# WWW path to download
bpqwww="http://www.cantab.net/users/john.wiseman/Downloads/Beta/${binary}"

#### End of Settings

function getwww() {
        wget ${bpqwww} -O ${bpqbin}/${binary}.tmp
}

function setup() {
	getwww
	chmod 755 "${bpqbin}/${binary}.tmp"
	chmod u+s "${bpqbin}/${binary}.tmp"
	version=`${bpqbin}/${binary}.tmp -v | grep Version | cut -d' ' -f 7`
	mv "${bpqbin}/${binary}.tmp" "${bpqbin}/${binary}.${version}"
	sudo setcap "CAP_NET_ADMIN=ep CAP_NET_RAW=ep CAP_NET_BIND_SERVICE=ep"  "${bpqbin}/${binary}.${version}"
	unlink "${bpqbin}/${binary}"
	ln -s "${bpqbin}/${binary}.${version}" "${bpqbin}/${binary}"

}

oldfile=`readlink -f ${bpqbin}/${binary}`

if [ ! -f ${oldfile} ]; 
then
	echo "No existing binary found, first run? ok"
	setup
else
	local=$(date -d "$( stat ${oldfile} | awk '/Modify/{gsub( /^[^:]+: +/,"",$0); print}' )" "+%s")
	remote=$(date -d "$( curl -sI ${bpqwww} | awk '/last-modified/{gsub( /^[^:]+: +/,"",$0); print}' )" "+%s")

	if [[ ${local} -lt ${remote} ]]
	then
		setup
		echo "Upgraded to version $version"
	else
		echo "Nothing to do"
		ls -l ${bpqbin}
	fi
fi
