#!/bin/bash 
#
#
# Settings
# Path to BPQ binary directory
bpqbin=$PWD/bpqbin
# Name of binary to pull as well as use
binary=pilinbpq
# WWW path to download
bpqwww="http://www.cantab.net/users/john.wiseman/Downloads/Beta/${binary}"

binstore=$PWD/bpqbin/archive
#### End of Settings

function download() {
        wget ${bpqwww} -O ${bpqbin}/${binary}.tmp
	chmod 755 "${bpqbin}/${binary}.tmp"
	#chmod u+s "${bpqbin}/${binary}.tmp"
	version=`${bpqbin}/${binary}.tmp -v | grep Version | cut -d' ' -f 7`
	if [ -z ${version} ];
       	then
		echo "Bad binary download"
		exit
	else
		echo Found version ${version}
	fi
	echo "Creating ${bpqbin}/${binary}.${version}"
	mv "${bpqbin}/${binary}.tmp" "${bpqbin}/${binary}.${version}"
	if [[ ! -d ${binstore} ]]; then
		mkdir -p ${binstore}
	fi
	echo "Copying to Archive"
	cp "${bpqbin}/${binary}.${version}" $binstore
	echo "Compressing"
	gzip "$binstore/${binary}.${version}"
	echo "Setting Permissions on ${bpqbin}/${binary}.${version}"
	sudo setcap "CAP_NET_ADMIN=ep CAP_NET_RAW=ep CAP_NET_BIND_SERVICE=ep"  "${bpqbin}/${binary}.${version}"
	echo "Linking..."
	unlink "${bpqbin}/${binary}"
	ln -s "${bpqbin}/${binary}.${version}" "${bpqbin}/${binary}"
	echo "Complete"

}

oldfile=`readlink -f ${bpqbin}/${binary}`

if [ ! -f ${oldfile} ]; 
then
	echo "No existing binary found"
	download
else
	filedate=$(date -d "$( stat ${oldfile} | awk '/Modify/{gsub( /^[^:]+: +/,"",$0); print}' )" "+%s")
	echo "Local file date: ${filedate}"
	filedate_remote=$(date -d "$( curl -sI ${bpqwww} | awk '/last-modified/{gsub( /^[^:]+: +/,"",$0); print}' )" "+%s")
	echo "Remote file date: ${filedate_remote}"

	if [[ ${filedate} -lt ${filedate_remote} ]]
	then
		download
		echo "Upgraded to version $version"
	else
		echo "Nothing to do"
		ls -l ${bpqbin}
	fi
fi
